### ISSUE TITLE
我觉得你是在贡献列表写字

### ISSUE THREAD

**Issue by cyb233** [lyy289065406/lyy289065406#9]
但我没有证据😂
![20220531171217](https://user-images.githubusercontent.com/39186981/171138827-84f52d19-a345-41f3-96e4-ba5b7917ae8f.png)

**Comment by hksanduo** [comment]
这个操作yyds

**Comment by cyb233** [comment]
![image](https://user-images.githubusercontent.com/39186981/176884468-c4d7408b-2336-48f1-b1bd-b8773285c8f8.png)

**Comment by lyy289065406** [comment]
> ![image](https://user-images.githubusercontent.com/39186981/176884468-c4d7408b-2336-48f1-b1bd-b8773285c8f8.png)

是在写字，参考这个工程：如何用一年画一幅字符画
https://github.com/lyy289065406/crop-circles

**Comment by lyy289065406** [comment]
> 这个操作yyds

参考这个工程：如何用一年画一幅字符画：
https://github.com/lyy289065406/crop-circles
